stages:
  - build

Build image:
  # Official docker image.
  stage: build
  rules:
    - if: $CI_COMMIT_REF_SLUG == 'dev'
      variables:
        DOCKER_IMAGE_TAG: "latest"
      when: always
    - if: $CI_COMMIT_REF_SLUG != 'dev'
      variables:
        DOCKER_IMAGE_TAG: $CI_COMMIT_REF_SLUG
      when: always
    - when: never
  parallel:
    matrix:
      - TAG_BASE:
          - ""
          - "debug"
          - "profile"
  variables:
    container: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - if [ ! -z "$TAG_BASE" ]; then DOCKER_IMAGE_TAG="$TAG_BASE-$DOCKER_IMAGE_TAG"; fi
    - if [ -z "$TAG_BASE" ]; then COMPOSE_TARGET="image"; else COMPOSE_TARGET="$TAG_BASE"; fi
    - mkdir -p /kaniko/.docker
    - mv $DOCKER_AUTH_CONFIG /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/Dockerfile"
      --destination "$DOCKER_USER/$CI_PROJECT_NAME:$DOCKER_IMAGE_TAG"
      --target $COMPOSE_TARGET
      --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      --build-arg VCS_REF="$CI_COMMIT_SHA"
